# Generated by Django 2.1.7 on 2019-05-14 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_cd', models.CharField(blank=True, max_length=20, null=True)),
                ('title_ko', models.CharField(blank=True, max_length=100, null=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_tm', models.CharField(blank=True, max_length=50, null=True)),
                ('nation', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('actor1', models.CharField(blank=True, max_length=100, null=True)),
                ('actor2', models.CharField(blank=True, max_length=100, null=True)),
                ('actor3', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('audience', models.CharField(blank=True, max_length=100, null=True)),
                ('open_dt', models.CharField(blank=True, max_length=100, null=True)),
                ('poster_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('trailer_url', models.TextField(blank=True, null=True)),
                ('score_sum', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-average_score'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('value', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-value'],
            },
        ),
    ]
